{% set version = "1.3.0" %}

package:
  name: gecos
  version: {{ version }}

source:
  url: https://github.com/biotite-dev/gecos/archive/v{{ version }}.tar.gz
  sha256: 8ef587d735ca671bbd97d7b66fd6b2ae98032ad9cd2aef0edb711635c8b30f49

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - gecos = gecos.cli:main

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - python >=3.7
    - numpy >=1.13
    - biotite >=0.21
    - scikit-image >=0.17
    - matplotlib-base >=3.0

test:
  source_files:
    - tests/
  requires:
    - pytest
  commands:
    - pytest --ignore tests/test_version.py
    - gecos --help

about:
  home: https://gecos.biotite-python.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Generated color schemes for sequence alignment visualizations
  doc_url: https://gecos.biotite-python.org
  dev_url: https://github.com/biotite-dev/gecos

extra:
  recipe-maintainers:
    - padix-key
